### ISSUE TITLE
Can I use openwrt?

### ISSUE THREAD

**Issue by cnucky** [AlexBevan/go-openvpn-radius#1]
Can I use openwrt?

**Comment by AlexBevan** [comment]
![bitmoji](https://sdk.bitmoji.com/render/panel/f50560c3-3df4-436a-b21f-cc40d877d6e8-46cfaea5-0363-4ecf-868c-b39c67cc6831-v1.png?transparent=1&palette=1&width=246) I've not tested sorry dude
